### PR TITLE
Reuse single http connection per lambda instance

### PR DESCRIPTION
**Pull request by cornet**
Currently every time the ingester.py function is invoked an new https
connection is created. In basic testing after the function instance
had been created each request took ~200ms.

Switching out urllib2 for the "requests" library we can then create a
session outside of the main handler function will get re-used.
This dropped the time per request to 20ms and also means less
connections are made to the Humio cluster.

### CODE REVIEW

**Comment by cornet** [comment]
I've been running this for about a week without any errors on a dev account.

The main difference is the drop in execution time:

image

For us it mean that we were only being billed for 100ms request time (lambda rounds up to the nearest 100ms) rather than 300ms.

**Comment by pmech** [comment]
Cool. I'll merge

**Comment by siozosdr** [comment]
What is the status of this PR? Has it been merged?

**Comment by Suzanna-Volkov** [comment]
Hi @cornet 

I would like to merge your PR, but we have updated our license agreement for this project to Apache 2.0 as it didn't have one before, are you still cool with contributing the code?

**Comment by cornet** [comment]
Yup still happy for this to be merged @Suzanna-Volkov

**Pull request merged**
